version: '2'
services:
  nginx: 
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    hostname: boxn
    networks: 
    - mynet
    expose: 
    - 80
    ports:
    - 8080:80
    command: nginx
networks: 
  mynet: 
    driver: bridge
